import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const wgslDir = join(__dirname, '../src/wgsl');
const outputFile = join(__dirname, '../src/webgpu/wgsl-shaders.ts');

// Read all WGSL files
const wgslFiles = readdirSync(wgslDir).filter(file => file.endsWith('.wgsl'));

let output = '// Auto-generated file containing WGSL shaders as strings\n';
output += '// Do not edit this file manually!\n\n';

// Generate exports for each WGSL file
wgslFiles.forEach(file => {
  const name = file.replace('.wgsl', '');
  const content = readFileSync(join(wgslDir, file), 'utf8');
  // Escape backticks and other special characters
  const escapedContent = content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
  
  output += `export const ${name} = \`${escapedContent}\`;\n\n`;
});

writeFileSync(outputFile, output);
console.log(`Generated ${outputFile} with ${wgslFiles.length} WGSL shaders`);